site_name: GuradiOne Transformer
theme:
  name: 'rtd-dropdown'
# material or rtd-dropdown
pages:
  - Contents: docs/index.md
  - For Product Safety & Copyrights: docs/For Product Safety & Copyrights.md
  - Product Introduction: docs/Product Introduction.md
  - User Guide: docs/User Guide.md
  - FAQ: docs/FAQ.md
  - Troubleshooting and Customer Service: docs/Troubleshooting and Customer Service.md
  - Appendix: docs/Appendix.md

site:
    git checkout mkdocs
    mkdocs build
    git checkout master
    cp -R site/* .
    rm -rf site
    echo Ready to commit and push